language: php
php:
  - 5.5
  - 5.6
  - hhvm
branches:
  only:
    - master
install:
  - composer selfupdate
  - composer install --prefer-source
  - if [ "$TRAVIS_PHP_VERSION" == 'hhvm' ]; then
      sed -i '/PhpSpec\\Extension\\CodeCoverageExtension/d' phpspec.yml.dist;
    fi;
script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpspec run
after_success:
  - if [ "$TRAVIS_PHP_VERSION" == '5.6' ]; then
      wget https://scrutinizer-ci.com/ocular.phar;
      php ocular.phar code-coverage:upload --format=php-clover build/reports/phpspec.xml;
      php ocular.phar code-coverage:upload --format=php-clover build/reports/phpunit.xml;
    fi;