language: php
php:
  - 5.5
  - 5.6
  - hhvm
branches:
  only:
    - master
install:
  - composer selfupdate
  - composer install --prefer-source
script:
  - ./vendor/bin/phpunit
after_success:
  - if [ "$TRAVIS_PHP_VERSION" == '5.6' ]; then
      wget https://scrutinizer-ci.com/ocular.phar;
      php ocular.phar code-coverage:upload --format=php-clover build/reports/phpunit.xml;
    fi;